"""create savings table

Revision ID: cc9f53e3442e
Revises: af3219f3b92b
Create Date: 2026-09-27 23:33:20.110280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc9f53e3442e'
down_revision: Union[str, Sequence[str], None] = 'af3219f3b92b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('savings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('savings_type', sa.Enum('INCOME', 'SIP', 'INVESTMENT', 'OTHER', name='savingstypeenum'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('created_ate', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_savings_id'), 'savings', ['id'], unique=True)
    op.create_index(op.f('ix_savings_user_id'), 'savings', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_savings_user_id'), table_name='savings')
    op.drop_index(op.f('ix_savings_id'), table_name='savings')
    op.drop_table('savings')
    # ### end Alembic commands ###
